services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data: